# main menu navigation
menu:
  home: /
  archives: /archives
  about: /about
  friend: /friend

banner: "images/banner.jpg" # themes/reimu/source/css/images/banner.jpg
favicon: "images/favicon.ico" # themes/reimu/source/css/images/favicon.ico
avatar: "avatar.jpg" # source/_data/avatar/avatar.jpg

# Content
excerpt_link: Read More
fancybox: true

# rss
# need https://github.com/hexojs/hexo-generator-feed
rss: atom.xml

# Footer
copyright:
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# You can use html like below...
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Sidebar
sidebar: right
widgets:
- category
#- tag
- tagcloud
- archive
#- recent_posts

# Widget behavior
archive_type: 'monthly'
show_count: false
recent_posts_limits: 5

social:
  github: https://github.com/yourname
  google: https://plus.google.com/yourname
  twitter: https://twitter.com/yourname
  facebook: https://www.facebook.com/yourname

footer:
  since: 2020 # 2020-current_year
  powered: true
  count: true
  busuanzi: true

# need https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus
# use katex
math:
  enable: false

# need https://github.com/webappdevelp/hexo-filter-mermaid-diagrams
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: false  # default true

# valine comment system. https://valine.js.org
# version 1.5.1
# notify and verify have been deprecated
valine:
  enable: false # if you want to use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  pageSize: 10 # comment list page size
  avatar: mp # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
  recordIP: true # whether to record the IP address of the commenters
  highlight: true # whether to highlight the code blocks

# need https://github.com/thom4parisot/hexo-algolia
# please add the following config in your _config.yml
# algolia:
#   applicationID: 'your applicationID'
#   apiKey: 'your apiKey'
#   adminApiKey: 'your adminApiKey'
#   indexName: 'your indexName'
#   chunkSize: 5000
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: "搜索....."
    hits_empty: "未发现与 「${query}」相关内容"
    hits_stats: "找到${hits}条结果（用时 ${time} ms）"

# Dependent cdn links
vendor:
  js:
    jquery: https://unpkg.com/jquery@3.6.3/dist/jquery.min.js
    clipboard: https://unpkg.com/clipboard@2.0.11/dist/clipboard.min.js
    lazysizes: https://unpkg.com/lazysizes@5.3.2/lazysizes.min.js
    fancybox: https://unpkg.com/@fancyapps/ui@4.0/dist/fancybox.umd.js
    valine: https://unpkg.com/valine@1.5.1/dist/Valine.min.js
    busuanzi: https://unpkg.com/busuanzi@2.3.0/bsz.pure.mini.js
    algolia: https://unpkg.com/algoliasearch@4.14.2/dist/algoliasearch-lite.umd.js
    instantsearch: https://unpkg.com/instantsearch.js@1.5.1/dist/instantsearch.min.js
    pace: https://unpkg.com/pace-js@1.2.4/pace.min.js
    mermaid: https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  css:
    highlight: https://cdn.jsdelivr.net/npm/typeface-source-code-pro@0.0.71/index.min.css
    fancybox: https://unpkg.com/@fancyapps/ui/dist/fancybox.css
    katex: https://unpkg.com/katex@0.16.4/dist/katex.min.css
